#!/usr/bin/env bash
# This bash script will transfer a file from my a client to a server
if [ $# -lt 4 ]; then
   echo "Usage: transfer PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
	scp -o StrictHostKeyChecking=no -i "$4" "$1" "$3"@"$2":~/
fi
